#!/usr/bin/env python3
"""Inject deploy-only metadata into the prebuilt Welcome Home pages.

Titles, descriptions, canonicals, Open Graph, Twitter and JSON-LD are all
generated by generate_site.py and committed, so the files in site/ are already
what gets served. The only thing that cannot live in the repo is the Search
Console verification token, which arrives as a build environment variable.
"""
from __future__ import annotations

import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SITE = ROOT / "site"
VERIFY = os.getenv("GOOGLE_SITE_VERIFICATION", "").strip()


def inject(page: Path, tag: str) -> bool:
    text = page.read_text(encoding="utf-8")
    if 'name="google-site-verification"' in text:
        return False
    if "</head>" not in text:
        raise RuntimeError(f"missing </head> in {page}")
    page.write_text(text.replace("</head>", f"{tag}\n</head>", 1), encoding="utf-8")
    return True


def main() -> int:
    pages = sorted(SITE.rglob("*.html"))
    if not pages:
        raise RuntimeError("no HTML pages found under site/")
    if not VERIFY:
        print(f"SEO enhancement: {len(pages)} pages already carry their metadata; "
              "no GOOGLE_SITE_VERIFICATION set, nothing to inject")
        return 0
    tag = f'<meta name="google-site-verification" content="{VERIFY}">'
    changed = sum(1 for page in pages if inject(page, tag))
    print(f"SEO enhancement: verification tag added to {changed}/{len(pages)} pages")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
